### ISSUE TITLE
A few bugs on mobile :/

### ISSUE THREAD

**Issue by Br0ad** [sk7725/BetaMindy#63] opened 2021-07-15 12:54 UTC
1:when grabbing with a claw you crash 
Log: Mindustry has crashed. How unfortunate.
Version: pre-alpha build 128
OS: Linux x32
Java Version: 0
Java Architecture: null
12 Mods: betamindy:1.0
[#b59e72]Demo of Chaos Itself[], ldb:1.3.1, mutl:1.3.0, override-lib:1.0.1, test-utils:0.14, zooooooooom:1, btm:2.4.21, heavy-armaments:2.6, hori:[blue]3.5.1[], simple-additions:1.3.7, time-control:0.2, units-mod:1.0

> NoSuchMethodError: 'No virtual method icon(Lmindustry/ui/Cicon;)Larc/graphics/g2d/TextureRegion; in class Lmindustry/world/blocks/payloads/BuildPayload; or its super classes (declaration of 'mindustry.world.blocks.payloads.BuildPayload' appears in base.apk)'
Claw$ClawBuild.drawClaw: 327
Claw$ClawBuild.draw: 339
Block.drawBase: 269
BlockRenderer.drawBlocks: 327
Renderer.draw: 266
Renderer.update: 119
ApplicationCore.update: 37
ClientLauncher.update: 174
AndroidGraphics.onDrawFrame: 374
GLSurfaceView$GLThread.guardedRun: 1571
GLSurfaceView$GLThread.run: 1270

2: When entering a pipe on mobile:
Log: Mindustry has crashed. How unfortunate.
Version: pre-alpha build 128
OS: Linux x32
Java Version: 0
Java Architecture: null
12 Mods: betamindy:1.0
[#b59e72]Demo of Chaos Itself[], ldb:1.3.1, mutl:1.3.0, override-lib:1.0.1, test-utils:0.14, zooooooooom:1, btm:2.4.21, heavy-armaments:2.6, hori:[blue]3.5.1[], simple-additions:1.3.7, time-control:0.2, units-mod:1.0

> NoSuchMethodError: 'No virtual method icon(Lmindustry/ui/Cicon;)Larc/graphics/g2d/TextureRegion; in class Lmindustry/world/blocks/payloads/UnitPayload; or its super classes (declaration of 'mindustry.world.blocks.payloads.UnitPayload' appears in base.apk)'
ClearPipe$UnitinaBottle.datBigBoi: 425
ClearPipe$UnitinaBottle.<init>: 405
ClearPipe$ClearPipeBuild.acceptUnit: 206
ClearPipe$ClearPipeBuild.lambda$suck$0$ClearPipe$ClearPipeBuild: 180
-$$Lambda$ClearPipe$ClearPipeBuild$2dAtPHQv9u7QDAkcJGPEcDfWG_8.get: 8
QuadTree.intersect: 180
EntityGroup.intersect: 116
Units.nearby: 355
ClearPipe$ClearPipeBuild.suck: 178
ClearPipe$ClearPipeBuild.update: 251
EntityGroup.update: 59
Groups.update: 71
Logic.update: 421
ApplicationCore.update: 37
ClientLauncher.update: 174
AndroidGraphics.onDrawFrame: 374
GLSurfaceView$GLThread.guardedRun: 1571
GLSurfaceView$GLThread.run: 1270
Last one. When using a block furnace on mobile:
Log:
Mindustry has crashed. How unfortunate.
Version: pre-alpha build 128
OS: Linux x32
Java Version: 0
Java Architecture: null
12 Mods: betamindy:1.0
[#b59e72]Demo of Chaos Itself[], ldb:1.3.1, mutl:1.3.0, override-lib:1.0.1, test-utils:0.14, zooooooooom:1, btm:2.4.21, heavy-armaments:2.6, hori:[blue]3.5.1[], simple-additions:1.3.7, time-control:0.2, units-mod:1.0

> NoSuchMethodError: 'No virtual method icon(Lmindustry/ui/Cicon;)Larc/graphics/g2d/TextureRegion; in class Lmindustry/world/blocks/payloads/BuildPayload; or its super classes (declaration of 'mindustry.world.blocks.payloads.BuildPayload' appears in base.apk)'
PayloadFactory$PayloadFactoryBuild.lambda$null$0$PayloadFactory$PayloadFactoryBuild: 221
-$$Lambda$PayloadFactory$PayloadFactoryBuild$kbFS4gNu83tvEhxfVYPI8vR8zps.get: 2
Table.image: 370
PayloadFactory$PayloadFactoryBuild.lambda$displayBars$8$PayloadFactory$PayloadFactoryBuild: 221
-$$Lambda$PayloadFactory$PayloadFactoryBuild$vfHMKgsZ7asBhJ1911TOhQNDNQY.get: 4
Table.table: 264
PayloadFactory$PayloadFactoryBuild.displayBars: 220
Building.lambda$display$5: 315
Building.$r8$lambda$Nrj5LochsNBGlRMbbmmEBQRaUs4: 0
Building$$ExternalSyntheticLambda2.get: 4
Table.table: 264
Building.display: 313
PlacementFragment.lambda$build$20: 359
PlacementFragment.$r8$lambda$8uQfl543dMO8FA1UsMchJwLOumg: 0
PlacementFragment$$ExternalSyntheticLambda10.get: 4
Cell.lambda$update$0: 171
Cell.$r8$lambda$SYmv5pp0-n9ePhu8GjGqyCjg1VU: 0
Cell$$ExternalSyntheticLambda1.run: 4
Element.act: 79
Group.act: 37
Group.act: 41
Group.act: 41
Group.act: 41
Group.act: 41
Group.act: 41
Scene.act: 193
Scene.act: 139
UI.update: 142
ApplicationCore.update: 37
ClientLauncher.update: 174
AndroidGraphics.onDrawFrame: 374
GLSurfaceView$GLThread.guardedRun: 1571
GLSurfaceView$GLThread.run: 1270
Man I'm so sorry for the bugs

**Comment by sk7725** [comment] 2021-07-15 13:08
Man its okay
also duplicate of #64 (well actually you were first but pyguy decided to DM me)

**Comment by sk7725** [comment] 2021-07-15 13:09
Conclusion: wait for Mindustry v129 or just use Mindustry v6

**Closed by sk7725** 2021-07-15 13:08 UTC
