### ISSUE TITLE
Mindustry crashes when i add the mod

### ISSUE THREAD

**Issue by danikkz** [sk7725/BetaMindy#59] opened 2021-06-23 18:15 UTC
**Platform**: *Windows

**Build**: *21282*

**Mod Version**: *0.955*

**Issue**: *After i added the jar file from builds in the mod folder, mindustry crashed while loading. When i opened the game again, it said it disabled all the mods because they were the reason it crased (i tried betamindy alone, still crashed) and mindustry worked just fine.*

**Steps to reproduce**: *Add the betamindy.jar file in mod folder, open the game.*

**Save file**: *Not required.*

**Last log**: *Block wasnt a reason.*

**Crash logs**: *Mindustry has crashed. How unfortunate.
Version: bleeding-edge build 21282
OS: Windows 10 x32
Java Version: 1.8.0_291
Java Architecture: 32
9 Mods: betamindy:0.9
[#b59e72]Demo of Chaos Itself[], dev-mode:2.3.1, ui-lib:2.16.6, unit-factory:2.4.2, anuke-logic:1.9.0, cmd:0.2, goldmod:2.0 alpha b14, invincible-cheat-mod-v6:2.8.1, lol:6.9

java.lang.NoSuchFieldError: game
	at betamindy.content.SettingAdder.addGameSetting(SettingAdder.java:11)
	at betamindy.content.SettingAdder.init(SettingAdder.java:18)
	at betamindy.BetaMindy.lambda$new$3(BetaMindy.java:51)
	at arc.Events.lambda$fire$2(Events.java:31)
	at arc.struct.Seq.each(Seq.java:200)
	at arc.Events.fire(Events.java:31)
	at arc.Events.fire(Events.java:26)
	at mindustry.ClientLauncher.update(ClientLauncher.java:152)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:166)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:154)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:46)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38).*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sk7725** [comment] 2021-06-25 10:13
uh @Anuken your settings reflection thingy isnt working as intended...?
anyways, cannot fix as the package has been changed in 7.0 and 8 have no idea how

**Comment by Anuken** [comment] 2021-06-25 13:21
@sk7725 Version 0.955 doesn't have any of my code in it. My PR was made long after that release.

**Comment by sk7725** [comment] 2021-06-26 11:38
oh right I forgot. Will be fixed in BetaMindy 1.0 then, hopefully.

**Closed by sk7725** 2021-06-26 11:38 UTC
Labels: bug
