### ISSUE TITLE
Crash when I enter a clear pipe

### ISSUE THREAD

**Issue by Weptlogdotzip1** [sk7725/BetaMindy#66] opened 2021-07-15 17:11 UTC
**Platform**: *Android right now, idk about other platforms*

**Build**: *128*

**Mod Version**: *1.0*

**Issue**: *it crashes when I enter a clear pipe.*

**Steps to reproduce**: *just try to enter a clear pipe. Its simple.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. Not required, but you will be asked for it in certain bugs.*

**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain block is not working at ALL, usually the case in headless servers.*

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [ ] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sk7725** [comment] 2021-07-15 22:41
duplicate of #64 
(the reasons are the same)

**Closed by sk7725** 2021-07-15 22:41 UTC
Labels: bug
